spring.application.name: hello-spring-consumer
spring.profiles.active: local

spring:
  config:
    import:
      - logging.yml
      - db-main.yml
      - consumer.yml
      - example-client.yml
      - admin-api-client.yml
---
spring.config.activate.on-profile: local

---
spring.config.activate.on-profile: local-dev

---
spring.config.activate.on-profile: dev

---
spring.config.activate.on-profile: staging

---
spring.config.activate.on-profile: live

