### Application Version
applicationVersion=0.0.1

### Project Config
projectGroup=me.jimmy

### Project Dependency version
kotlinVersion=1.8.22
ktLinter=12.1.0

### Spring Dependency version
springBootVersion=3.3.2
springDependencyManagementVersion=1.1.6
springCloudDependenciesVersion=2023.0.3

### mock
mockkVersion=1.13.7