### Application Version
applicationVersion=0.0.1

### Project Config
projectGroup=me.jimmy

### Project Dependency version
kotlinVersion=1.8.22
ktLinter=12.1.0

### Spring Dependency version
springBootVersion=3.3.6
springDependencyManagementVersion=1.1.5
springCloudDependenciesVersion=2023.0.4

### External Dependency version
jacksonVersion=2.18.1

### mock
mockkVersion=1.13.7