spring.application.name: hello-spring-api
spring.profiles.active: local
        
spring:
  config:
    import:
      - logging.yml
      - monitoring.yml
      - db-main.yml
      - admin-api-client.yml


custom:
  user: jaeyeon

kafka:
  producer:
    bootstrapServer: localhost:9092,localhost:9093,localhost:9094
    topic: test-topic

logging:
  level:
    root: info
---
spring.config.activate.on-profile: local

---
spring.config.activate.on-profile: local-dev

---
spring.config.activate.on-profile: dev

---
spring.config.activate.on-profile: staging

---
spring.config.activate.on-profile: live

