spring.application.name: hello-spring-api
spring.profiles.active: local
        
spring:
  config:
    import:
      - logging.yml
      - db-main.yml


custom:
  user: jaeyeon

logging:
  level:
    root: debug
---
spring.config.activate.on-profile: local

---
spring.config.activate.on-profile: local-dev

---
spring.config.activate.on-profile: dev

---
spring.config.activate.on-profile: staging

---
spring.config.activate.on-profile: live

